language: node_js
node_js: "6"

after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    if ([ "$TRAVIS_BRANCH" == "master" ] || [ ! -z "$TRAVIS_TAG" ]) &&
      [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
        echo "Deploying"

        cd "$TRAVIS_BUILD_DIR"
        npm run build
        cd dist
        git clone https://danielbraithwt:$GITHUB_API_KEY@github.com/danielbraithwt/danielbraithwt.github.io.git
        rm -rf danielbraithwt.github.io/static/
        rm danielbraithwt.github.io/index.html
        cp index.html danielbraithwt.github.io/
        cp -r static danielbraithwt.github.io/
        cd danielbraithwt.github.io
        git add -A ./
        git -c user.name="travis" -c user.email="travis" commit -m "Auto build"
        git push -f
      else
        echo "Not Deploying"
      fi
  fi
